NUM_EPOCHS = 100
HIDDEN_SIZE = 256
NUM_LAYERS = 2
ENCODER_DROPOUT = 0.5
DECODER_DROPOUT = 0.5
BATCH_SIZE = 128
LR = 0.0001
TEACHER_FORCING_EPOCHS = 20
DEVICE = "cuda"

TRAIN_PATH = "train.txt"
TEST_PATH = "train.txt"
VOCAB_PATH_HINDI = "vocab_hindi.pickle"
VOCAB_PATH_ENGLISH = "vocab_hindi.pickle"
